### ISSUE TITLE
Start NewConcesatio Error

### ISSUE THREAD

**Issue by BogdanJak** [magols/BlazorGPT#12]
When I try to start a new conversation, I get the following error.
![image](https://github.com/magols/BlazorGPT/assets/54505464/1b05a8df-7cc2-472c-8203-d612c81da6ed)

Below are my settings in the appsettings file
![image](https://github.com/magols/BlazorGPT/assets/54505464/b3f2da42-df87-4504-9188-bd41907c0d2b)

I'm using the latest version

**Comment by magols** [comment]
I think this should be fixed by this https://github.com/magols/BlazorGPT/commit/acd06cf394f91b91d30f0501b2394d78d6d144fc

**Comment by BogdanJak** [comment]
Hello
Thanks very much - one less problem.
However, another one appeared. I am logged in, I have created a new profile. After sending sample text to Chat, I receive the following error.
![image](https://github.com/magols/BlazorGPT/assets/54505464/beaa6824-7b65-4261-8010-d90618d72449)
My appsettings content

`"Logging": {
  "LogLevel": {
    "Default": "Information",
    "Microsoft.AspNetCore": "Warning",
    "Microsoft.EntityFrameworkCore": "Warning"

  }
},
"AllowedHosts": "*",
"AzureWebjobsStorage": "UseDevelopmentStorage=true",



"PipelineOptions": {
  "Model": "gpt-4",
  "Models": [ "gpt-3.5-turbo", "gpt-4" ], // gpt-35-turbo for Azure OpenAI
  "ModelEmbeddings": "text-embedding-ada-002",
  "ModelTextCompletions": "text-davinci-003",
  "MaxTokens": 2500,
  "KrokiHost": "https://kroki.io",
  "EnabledInterceptors": [ "Plugins", "Json Hive State", "Structurizr Hive DSL", "State has changed" ],
  "PreSelectedInterceptors": [],

  "FileUpload": {
    "Enabled": false
  },

  "PipelineOptions:Bot": {
    "BotSystemInstruction": "You are a helpful assistant",
    "BotUserId": "[set id]",
    "FileUpload": {
      "Enabled": false
    }
  },

  "Embeddings:RedisConfigurationString": "localhost",
  "Embeddings:RedisIndexName": "blazorgpt_idx",
  "Embeddings:MaxTokensToIncludeAsContext": 1600,

  "Embeddings:UseRedis": false,
  "Embeddings:UseSqlite": false,
  "Embeddings:SqliteConnectionString": "",

  "BING_API_KEY": "[get a key]",
  "GOOGLE_API_KEY": "[get a key]",
  "GOOGLE_SEARCH_ENGINE_ID": "[get an id]",


  "PipelineOptions:serviceType": "OpenAI", //AzureOpenAI or  OpenAI
  "PipelineOptions:Model": "gpt-4-turbo",
  "PipelineOptions:ModelEmbeddings": "text-embedding-ada-002",
  "PipelineOptions:ModelTextCompletions": "davinci-002text-davinci-003",
  "PipelineOptions:Models": [ "gpt-35-turbo", "gpt-4", "gpt-4-turbo" ],
  "PipelineOptions:endpoint": "https://[yourendpoint}].openai.azure.com/", // only if using AzureOpenAI
  "PipelineOptions:apiKey": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "PipelineOptions:orgId": ""

},
"ConnectionStrings:BlazorGptDB": "Data Source=.;Initial Catalog=GPT1;Trusted_Connection=True; TrustServerCertificate=True; Persist Security Info=True;User ID=sa;Password=***;",

"ConnectionStrings:UserDB": "Data Source=.;Initial Catalog=GPT2;Trusted_Connection=True; TrustServerCertificate=True; Persist Security Info=True;User ID=sa;Password=***;",
"OpenAIServiceOptions:ApiKey": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`

**Comment by ScheppKrauss** [comment]
It is a Problem in the appsettings.json 

 "PipelineOptions": {
here add "serviceType": "OpenAI", //AzureOpenAI or  OpenAI
and
 "apiKey":

I think magols will fix it :)

**Comment by magols** [comment]
I have reworked the provider/model appsettings a bit. Now it should be a bit more clear in the config how to use it I hope. You can also configure both OpenAI and Azure OpenAI and use both of them without restarting the application. You can configure between the two (and which models to use) and your setting is stored in your browsers LocalStorage.

**Comment by BogdanJak** [comment]
I'm doing something else wrong. I use "ChatModel": "gpt-3.5-turbo". I receive an answer to any question I ask

`You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors. Status: 429 (Too Many Requests) ErrorCode: insufficient_quota

Content: { "error": { "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: [https://platform.openai.com/docs/guides/error-codes/api-errors."](https://platform.openai.com/docs/guides/error-codes/api-errors.%22), "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

Headers: Date: Mon, 01 Jan 2024 16:23:39 GMT Connection: keep-alive Vary: REDACTED X-Request-ID: REDACTED Strict-Transport-Security: REDACTED CF-Cache-Status: REDACTED Set-Cookie: REDACTED Server: cloudflare CF-RAY: REDACTED Alt-Svc: REDACTED Content-Type: application/json; charset=utf-8 Content-Length: 337`

ChatGPT launched through a browser on the same account works correctly.
I don't know if I'm doing something wrong?

**Comment by magols** [comment]
The OpenAI API has litte or nothing to do with ChatGPT. It also has it's own pricing and billing. 

I have seen others get this error and it's then because they have not set up billing (payment method) correctly  for their account as per https://platform.openai.com/account/billing/
